In [ ]:
# =====================================================
# IMPORTANDO LIBRERIAS
# =====================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# =====================================================
# CONFIGURACION DE DISPLAY Y GRAFICAS
# =====================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
plt.rcParams["figure.figsize"] = (10,6)

## Data Acquisition

In [ ]:
# Importar la librería de Supabase y dotenv para manejar variables de entorno
from supabase import create_client
from dotenv import load_dotenv

import os

In [3]:
# Cargar variables de entorno desde el archivo .env
load_dotenv()

True

### Conexión a Database

In [4]:
# Leer las variables de entorno
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

In [5]:
# Creando el cliente de Supabase
supabase = create_client(
    SUPABASE_URL,
    SUPABASE_KEY
)

In [7]:
# Validación de la creación del cliente de Supabase
if SUPABASE_URL and SUPABASE_KEY:
    print("✅ Supabase client created successfully.")
else:
    print("❌ Failed to load environment variables.")

✅ Supabase client created successfully.

### Extracción de datos desde Supabase

In [9]:
# Consulta SQL Customers

customers_response = (
    supabase
    .table("customers")
    .select("*")
    .execute()
)

customers_df = pd.DataFrame(customers_response.data)

In [10]:
# Consulta SQL Vehicles

vehicles_response = (
    supabase
    .table("vehicles")
    .select("*")
    .execute()
)

vehicles_df = pd.DataFrame(vehicles_response.data)

In [11]:
# Consulta SQL Loans

loans_response = (
    supabase
    .table("loans")
    .select("*")
    .execute()
)

loans_df = pd.DataFrame(loans_response.data)

- customers_df = Clientes.
- vehicles_df = Inventario financiable.
- loands_df = Operaciones financieras

In [20]:
# Función para hacer preview futuro a DataFrames
def preview_dataframe(df, name):
    """
    Muestra información básica sobre el dataframe dado.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame a inspeccionar.
    name : str
        Nombre amigable utilizado en la salida.
    """
    
    print("=" * 60)
    print(f"{name}")
    print("=" * 60)
    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")
    
    display(df.head())

In [21]:
# Prueba de función preview_dataframe
preview_dataframe(customers_df, "Customers")
preview_dataframe(vehicles_df, "Vehicles")
preview_dataframe(loans_df, "Loans")

============================================================
Customers
============================================================
Rows    : 1,000
Columns : 11

,customer_id,full_name,age,monthly_income,employment_years,credit_score,debt_to_income,region,customer_segment,risk_segment,created_at
0,1,Pablo Angulo,30,19945.0,0,530,0.42,Puebla,Economic,High Risk,2026-05-31T08:30:47.122026
1,2,Micaela Rivero,54,38228.0,10,650,0.35,Sinaloa,Economic,Medium Risk,2026-05-31T08:30:47.122026
2,3,Germán Barraza,31,17521.0,2,519,0.34,Jalisco,Economic,High Risk,2026-05-31T08:30:47.122026
3,4,Gilberto del Río,25,34618.0,2,553,0.53,Chihuahua,Economic,High Risk,2026-05-31T08:30:47.122026
4,5,Rebeca Sáenz,35,98140.0,10,742,0.45,Puebla,Standard,Medium Risk,2026-05-31T08:30:47.122026

============================================================
Vehicles
============================================================
Rows    : 20
Columns : 11

,vehicle_id,brand,model,vehicle_type,fuel_type,model_year,original_msrp,current_value,depreciation_rate,risk_category,created_at
0,1,Mercedes-Benz,CLA 200,Sedan,Gasoline,2022,720000.0,560655.36,0.08,Low,2026-05-31T08:20:12.091735
1,2,Mercedes-Benz,CLA 200,Sedan,Gasoline,2023,720000.0,609408.00,0.08,Low,2026-05-31T08:20:12.091735
2,3,Mercedes-Benz,CLA 200,Sedan,Gasoline,2024,720000.0,662400.00,0.08,Low,2026-05-31T08:20:12.091735
3,4,Mercedes-Benz,CLA 200,Sedan,Gasoline,2025,720000.0,720000.00,0.08,Low,2026-05-31T08:20:12.091735
4,5,Mercedes-Benz,A 35,Hatchback,Gasoline,2022,1200000.0,934425.60,0.08,Low,2026-05-31T08:20:12.091735

============================================================
Loans
============================================================
Rows    : 1,000
Columns : 12

,loan_id,customer_id,vehicle_id,loan_amount,down_payment,interest_rate,term_months,monthly_payment,approval_status,default_probability,loan_start_date,approved_or_rejected_on
0,1,8434,11,883246.48,128753.52,18.41,48,26135.23,Rejected,0.32,2022-12-14,2022-12-19
1,2,6212,4,551337.34,168662.66,15.17,36,19157.86,Approved,0.09,2022-01-21,2022-01-27
2,3,5154,4,599042.66,120957.34,16.19,60,14628.47,Approved,0.25,2023-08-03,2023-08-04
3,4,8186,7,856162.26,247837.74,16.94,60,21250.57,Rejected,0.22,2023-08-26,2023-08-30
4,5,3052,13,750133.01,378964.59,14.63,48,20734.56,Rejected,0.10,2023-09-22,2023-09-26

## Data Profiling

### Estructura del DataFrame

Objetivo:
- 10,000 filas
- 10 columnas
- Sin duplicados
- 2% valores nulos
- Variables numéricas
- Variables categóricas
- Calidad aceptable

In [22]:
# Función para mostrar información de columnas y tipos de datos
def profile_structure(df, name):
    """
    Muestra la información de estructura del DataFrame, incluyendo el número de filas, columnas y tipos de datos.
    """

    print("=" * 80)
    print(name)
    print("=" * 80)

    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")

    print("\nData Types")

    display(df.dtypes)

    print("\nDataFrame Info")

    df.info()

In [24]:
# Prueba de función profile_structure
profile_structure(customers_df, "Customers")
profile_structure(vehicles_df, "Vehicles")
profile_structure(loans_df, "Loans")

================================================================================
Customers
================================================================================
Rows    : 1,000
Columns : 11

Data Types

customer_id           int64
full_name               str
age                   int64
monthly_income      float64
employment_years      int64
credit_score          int64
debt_to_income      float64
region                  str
customer_segment        str
risk_segment            str
created_at              str
dtype: object

DataFrame Info
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1000 non-null   int64
 1   full_name         1000 non-null   str
 2   age               1000 non-null   int64
 3   monthly_income    1000 non-null   float64
 4   employment_years  1000 non-null   int64
 5   credit_score      1000 non-null   int64
 6   debt_to_income    1000 non-null   float64
 7   region            1000 non-null   str
 8   customer_segment  1000 non-null   str
 9   risk_segment      1000 non-null   str
 10  created_at        1000 non-null   str
dtypes: float64(2), int64(4), str(5)
memory usage: 86.1 KB
================================================================================
Vehicles
================================================================================
Rows    : 20
Columns : 11

Data Types

vehicle_id             int64
brand                    str
model                    str
vehicle_type             str
fuel_type                str
model_year             int64
original_msrp        float64
current_value        float64
depreciation_rate    float64
risk_category            str
created_at               str
dtype: object

DataFrame Info
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   vehicle_id         20 non-null     int64
 1   brand              20 non-null     str
 2   model              20 non-null     str
 3   vehicle_type       20 non-null     str
 4   fuel_type          20 non-null     str
 5   model_year         20 non-null     int64
 6   original_msrp      20 non-null     float64
 7   current_value      20 non-null     float64
 8   depreciation_rate  20 non-null     float64
 9   risk_category      20 non-null     str
 10  created_at         20 non-null     str
dtypes: float64(3), int64(2), str(6)
memory usage: 1.8 KB
================================================================================
Loans
================================================================================
Rows    : 1,000
Columns : 12

Data Types

loan_id                      int64
customer_id                  int64
vehicle_id                   int64
loan_amount                float64
down_payment               float64
interest_rate              float64
term_months                  int64
monthly_payment            float64
approval_status                str
default_probability        float64
loan_start_date                str
approved_or_rejected_on        str
dtype: object

DataFrame Info
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  1000 non-null   int64
 1   customer_id              1000 non-null   int64
 2   vehicle_id               1000 non-null   int64
 3   loan_amount              1000 non-null   float64
 4   down_payment             1000 non-null   float64
 5   interest_rate            1000 non-null   float64
 6   term_months              1000 non-null   int64
 7   monthly_payment          1000 non-null   float64
 8   approval_status          1000 non-null   str
 9   default_probability      1000 non-null   float64
 10  loan_start_date          1000 non-null   str
 11  approved_or_rejected_on  1000 non-null   str
dtypes: float64(5), int64(4), str(3)
memory usage: 93.9 KB

## Portfolio Overview

## Exploratory Data Analysis

## Executive Summary